# -*- coding: utf-8 -*-
"""
Created on Thu Feb 13 13:59:55 2020

@author: AsteriskAmpersand
"""
from collections import OrderedDict

monEnum = OrderedDict([
                        (0,"Anjanath"),
                        (1,"Rathalos"),
                        (4,"Zorah Magdaros"),
                        (7,"Great Jagras"),
                        (9,"Rathian"),
                        (10,"Pink Rathian"),
                        (11,"Azure Rathalos"),
                        (12,"Diablos"),
                        (13,"Black Diablos"),
                        (14,"Kirin"),
                        (16,"Kushala Daora"),
                        (17,"Lunastra"),
                        (18,"Teostra"),
                        (19,"Lavasioth"),
                        (20,"Deviljho"),
                        (21,"Barroth"),
                        (22,"Uragaan"),
                        (24,"Pukei-Pukei"),
                        (25,"Nergigante"),
                        (26,"Xeno'jiva"),
                        (27,"Kulu-Ya-Ku"),
                        (28,"Tzitzi-Ya-Ku"),
                        (29,"Jyuratodus"),
                        (30,"Tobi-Kadachi"),
                        (31,"Paolumu"),
                        (32,"Legiana"),
                        (33,"Great Girros"),
                        (34,"Odogaron"),
                        (35,"Radobaan"),
                        (36,"Vaal Hazak"),
                        (37,"Dodogama"),
                        (39,"Bazelgeuse"),
                        (61,"Tigrex"),
                        (62,"Nargacuga"),
                        (63,"Barioth"),
                        (64,"Savage Deviljho"),
                        (65,"Brachydios"),
                        (66,"Glavenus"),
                        (67,"Acidic Glavenus"),
                        (68,"Fulgur Anjanath"),
                        (69,"Coral Pukei-Pukei"),
                        (70,"Ruiner Nergigante"),
                        (71,"Viper Tobi-Kadachi"),
                        (72,"Nightshade Paolumu"),
                        (73,"Shrieking Legiana"),
                        (74,"Ebony Odogaron"),
                        (75,"Blackveil Vaal Hazak"),
                        (76,"Seething Bazelgeuse"),
                        (77,"Beotodus"),
                        (78,"Banbaro"),
                        (79,"Velkhana"),
                        (80,"Namielle"),
                        (81,"Shara Ishvalda"),
                        (88,"Gold Rathian"),
                        (89,"Silver Rathalos"),
                        (90,"Yian Garuga"),
                        (91,"Rajang"),
                        (93,"Brute Tigrex"),
                        (94,"Zinogre"),
                        (99,"Scarred Yian Garuga"),])